# Generated by Django 4.0.6 on 2022-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('power', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('illustration', models.URLField(blank=True)),
            ],
        ),
    ]
