# Generated by Django 4.0.6 on 2022-07-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardtype_remove_deck_cards_remove_card_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(to='cards.deck'),
        ),
    ]
