# Generated by Django 4.0.6 on 2022-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_deck_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='colors',
            field=models.JSONField(default=['black', 'white']),
        ),
    ]
