# Generated by Django 4.0.6 on 2022-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_deck_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.JSONField(default=['white']),
        ),
    ]
