# Generated by Django 4.0.6 on 2022-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='types',
            field=models.ManyToManyField(blank=True, to='cards.cardtype'),
        ),
    ]
