# Generated by Django 4.0.6 on 2022-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(related_name='cards', to='cards.deck'),
        ),
    ]
