# Generated by Django 4.0.6 on 2022-07-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_alter_deck_user_alter_playground_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='deck',
            field=models.ForeignKey(blank=True, default=0, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.deck'),
        ),
    ]
