# Generated by Django 4.0.6 on 2022-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_playground_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
