# Generated by Django 4.0.6 on 2022-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_playground_creation_date_playground_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='isLifeLink',
            field=models.BooleanField(default=False),
        ),
    ]
