# Generated by Django 4.0.6 on 2022-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_card_islifelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='po_de_depend',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
