# Generated by Django 4.0.6 on 2022-07-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_card_po_de_depend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='po_de_depend',
        ),
    ]
