# Generated by Django 4.0.6 on 2022-07-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_remove_card_po_de_depend'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
