# Generated by Django 4.0.6 on 2022-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_card_hashaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainsWalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('loyalty', models.CharField(max_length=4)),
                ('illustration', models.URLField(blank=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('colors', models.ManyToManyField(blank=True, to='cards.color')),
                ('deck', models.ManyToManyField(related_name='plainswalker', to='cards.deck')),
            ],
            options={
                'verbose_name': 'Plainswalker',
            },
        ),
    ]
