# Generated by Django 4.0.6 on 2022-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(max_length=4),
        ),
    ]
