# Generated by Django 4.0.6 on 2022-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_card_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='card',
            name='types',
        ),
        migrations.AddField(
            model_name='card',
            name='types',
            field=models.ManyToManyField(to='cards.cardtype'),
        ),
    ]
