# Generated by Django 4.0.6 on 2022-07-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_card_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Carte'},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'verbose_name': 'Type de carte'},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'Deck'},
        ),
    ]
