# Generated by Django 4.0.6 on 2022-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_options_alter_cardtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Couleur',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='colors',
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(to='cards.color'),
        ),
    ]
