# Generated by Django 4.0.6 on 2022-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_color_color_color_element_alter_card_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
